#!/bin/bash
# Build zotero-agent-mcp.xpi
# - wraps bridge/zotero-agent-mcp.mjs into plugin/bridge-source.js (jar-safe embedding)
# - wraps plugin/skill/SKILL.md into plugin/skill-source.js (released to the data dir at startup)
# - zips plugin/ into build/zotero-agent-mcp.xpi
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
export ROOT

node - <<'EOF'
const fs = require('fs');
const root = process.env.ROOT;
const src = fs.readFileSync(`${root}/bridge/zotero-agent-mcp.mjs`, 'utf8');
fs.writeFileSync(`${root}/plugin/bridge-source.js`,
  `// Auto-generated by tools/build.sh from bridge/zotero-agent-mcp.mjs — do not edit.\n` +
  `var BRIDGE_SRC = ${JSON.stringify(src)};\n`);
const skill = fs.readFileSync(`${root}/plugin/skill/SKILL.md`, 'utf8');
fs.writeFileSync(`${root}/plugin/skill-source.js`,
  `// Auto-generated by tools/build.sh from plugin/skill/SKILL.md — do not edit.\n` +
  `var SKILL_SRC = ${JSON.stringify(skill)};\n`);
console.log('bridge-source.js + skill-source.js generated');
EOF

mkdir -p "$ROOT/build"
rm -f "$ROOT/build/zotero-agent-mcp.xpi"
cd "$ROOT/plugin"
zip -q -r -X "$ROOT/build/zotero-agent-mcp.xpi" . -x "*.DS_Store"
echo "Built: $ROOT/build/zotero-agent-mcp.xpi"
unzip -l "$ROOT/build/zotero-agent-mcp.xpi" | tail -n +4 | head -12
